### ISSUE TITLE
attributes.py broken

### ISSUE THREAD

**Issue by cdkonecny** [pilotak/HomeAssistant-CustomComponents#11]
Something seems to have broken with this component when I went from 83.3 to 84.6.

Is there a way to tweak this to bring it back up?

I did update 
from homeassistant.helpers.restore_state import async_get_last_state
to
from homeassistant.helpers.restore_state import RestoreEntity

which eliminated the error but the entities are still not available....

**Comment by pilotak** [comment]
I will upgrade and see what i can do

**Comment by cdkonecny** [comment]
Thx.   It looks like the same adjustments made here do the trick.

https://github.com/rogro82/hass-variables/commit/6221f722ce3145ead976e3bdf171d302794ae8ff

**Comment by pilotak** [comment]
oh what a perfect link, i have fixed it
