### ISSUE TITLE
Can this be used with HACS?

### ISSUE THREAD

**Issue by tmchow** [pilotak/HomeAssistant-CustomComponents#14]
Now that HACS is now available, what's the right way to get `Attributes` installed via that way?

**Comment by pilotak** [comment]
Oh i didn't know that there is a new way of installing. I will have a look at it and let you know

**Comment by pilotak** [comment]
Quick install is to copy `attributes` folder from this repo over to `/custom_components/attributes` but i will setup a new repo for each of my components to accommodate HACS requirements and restructure for the bot to pick it up

**Comment by pilotak** [comment]
@tmchow merged https://github.com/custom-components/hacs/pull/258 you can now find it in a store
