### ISSUE TITLE
clientraw.py Fahrenheit to Celsius conversion

### ISSUE THREAD

**Issue by martinezpenya** [pilotak/HomeAssistant-CustomComponents#8]
In the clientraw.py sensor, your code translates from F to C, but this is not working because actual homeassistant has the unit_system: [metric|imperial] parameter and the system converts any input to this setting. So if we get C from clientraw.txt and we want to show F we have to put unit_system: imperial. And if we have F in clientraw.txt we can show C with unit_system: metric. So, we don't need conversion (actually it's showing the same value, because clientraw.py converts from C to F and homeassistant converts it to C again). I'm planning to add some new attributes to clientraw.py, if you want I could remove this type of conversions and clean the code.

**Comment by pilotak** [comment]
Thanks for the PRs. Now to units problem, i did't even realize that this option would have an effect on components as i never tried imperial units. I fine with you cleaning up the code, i will review it ASAP

**Comment by martinezpenya** [comment]
Here you have the PR #9
